imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
            
# Simple Rest        
geo:
    type:     rest
    resource: AppBundle\Controller\GeoController        

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_postgres
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
    
# REST Provider        
fos_rest:
    disable_csrf_role:    null
    access_denied_listener:

        # Prototype
        name:                 ~
    unauthorized_challenge:  null
    param_fetcher_listener:  false
    cache_dir:            '%kernel.cache_dir%/fos_rest'
    allowed_methods_listener:  false
    routing_loader:
        default_format:       null
        include_format:       true
    body_converter:
        enabled:              false
        validate:             false
        validation_errors_argument:  validationErrors
    service:
        router:               router
        templating:           templating
        serializer:           null
        view_handler:         fos_rest.view_handler.default
        exception_handler:    fos_rest.view.exception_wrapper_handler
        inflector:            fos_rest.inflector.doctrine
        validator:            validator
    serializer:
        version:              null
        groups:               []
        serialize_null:       false
    view:
        default_engine:       twig
        force_redirects:

            # Prototype
            name:                 ~
        mime_types:

            # Prototype
            name:                 ~
        formats:

            # Prototype
            name:                 ~
        templating_formats:

            # Prototype
            name:                 ~
        view_response_listener:  false
        failed_validation:    400
        empty_content:        204
        exception_wrapper_handler:  null
        serialize_null:       false
        jsonp_handler:
            callback_param:       callback
            callback_filter:      '/(^[a-z0-9_]+$)|(^YUI\.Env\.JSONP\._[0-9]+$)/i'
            mime_type:            application/javascript+jsonp
    exception:
        enabled:              true
        exception_controller:  'Symfony\Bundle\TwigBundle\Controller\ExceptionController::showAction' 
        codes:

            # Prototype
            name:                 ~
        messages:

            # Prototype
            name:                 ~
    body_listener:
        default_format:       null
        throw_exception_on_unsupported_content_type:  false
        decoders:

            # Prototype
            name:                 ~
        array_normalizer:
            service:              null
            forms:                false
    format_listener:
        rules:

            # URL path info
            path:                 null

            # URL host name
            host:                 null

            # Method for URL
            methods:              null
            stop:                 false
            prefer_extension:     true
            fallback_format:      html
            exception_fallback_format:  null
            priorities:           []
        media_type:
            version_regex:        '/(v|version)=(?P<version>[0-9\.]+)/'